import type {CategoryType,FilterState,Place,PriceLevel,VybeCategory} from '../types';
import {isGoogleMapsConfigured} from '../lib/env';
import {searchNearbyGooglePlaces,searchGooglePlacesText} from './googlePlaces';
import {haversineDistanceKm} from '../hooks/useGeolocation';
import {categoryOsmClauses,categorySearchTypes,legacyCategoryToCanonical,extractCategoryHint,evaluatePlaceRelevance,VYBE_CATEGORY_DEFINITIONS} from '../data/categoryTaxonomy';
export interface DiscoveryOptions{userLat?:number;userLng?:number;radiusKm?:number;searchQuery?:string;filters?:Partial<FilterState>}
const BAD_GOOGLE_TYPES=new Set(['airport','bus_station','train_station','transit_station','school','university','hospital','doctor','pharmacy','dentist','police','fire_station','courthouse','government_office','post_office']);
const MAX_RESULTS=100;
function targets(o:DiscoveryOptions):VybeCategory[]{const q=o.searchQuery?.trim()||o.filters?.searchQuery?.trim()||'';const c=extractCategoryHint(q);return c?[c]:[...new Set((o.filters?.categories??[]).flatMap(legacyCategoryToCanonical))]}
function dist(ps:Place[],lat?:number,lng?:number):Place[]{return ps.map(p=>({...p,distanceKm:lat!==undefined&&lng!==undefined&&Number.isFinite(p.location.lat)&&Number.isFinite(p.location.lng)?haversineDistanceKm(lat,lng,p.location.lat,p.location.lng):undefined}))}
export function deduplicatePlaces(ps:Place[]):Place[]{const m=new Map<string,Place>();for(const p of ps){if(!p.provider||!p.providerPlaceId)continue;m.set(`${p.provider}:${p.providerPlaceId}`,m.get(`${p.provider}:${p.providerPlaceId}`)??p)}return[...m.values()]}
function gate(ps:Place[],query:string,requested:VybeCategory[]):Place[]{return ps.map(p=>{const r=evaluatePlaceRelevance({provider:p.provider==='google'?'google':p.provider==='osm'?'osm':'vybe',providerPlaceId:p.providerPlaceId,providerTypes:p.providerTypes,providerPrimaryType:p.providerPrimaryType,canonicalCategory:p.canonicalCategory,name:p.name,query,requestedCategory:requested.length===1?requested[0]:null,distanceKm:p.distanceKm});return r.decision==='ACCEPT'?{...p,relevance:r,providerIdentityConfidence:r.providerIdentityConfidence,secondaryCategories:r.secondaryCategories}:null}).filter(Boolean) as Place[]}
function extras(ps:Place[],f?:Partial<FilterState>):Place[]{return ps.filter(p=>!f?.priceLevels?.length||f.priceLevels.includes(p.priceLevel)).filter(p=>!f?.moods?.length||f.moods.includes(p.primaryMood)).filter(p=>!f?.onlyOpenNow||p.openingHours.isOpenNow===true).filter(p=>!f?.onlyFree||p.features.isFree).filter(p=>!f?.onlyHiddenGems||p.features.isSecretGem).filter(p=>!f?.onlyLateNight||p.features.isLateNight).filter(p=>f?.maxDistanceKm===undefined||(p.distanceKm??Infinity)<=f.maxDistanceKm).filter(p=>!f?.companion||p.suitableFor.includes(f.companion))}
function rank(ps:Place[],sort:FilterState['sortBy']='vybe-score'){const pr:Record<PriceLevel,number>={free:0,'$':1,'$$':2,'$$$':3,'$$$$':4};return[...ps].sort((a,b)=>sort==='distance'?(a.distanceKm??Infinity)-(b.distanceKm??Infinity):sort==='rating'?(b.rating-a.rating)||(a.distanceKm??Infinity)-(b.distanceKm??Infinity):sort==='price-asc'?pr[a.priceLevel]-pr[b.priceLevel]:b.baseVybeScore-a.baseVybeScore)}
async function google(o:DiscoveryOptions,t:VybeCategory[]):Promise<Place[]>{if(!isGoogleMapsConfigured||o.userLat===undefined||o.userLng===undefined)return[];const q=o.searchQuery?.trim()||o.filters?.searchQuery?.trim()||'',r=o.radiusKm??5,out:Place[]=[];const add=async(fn:Promise<Place[]>)=>{try{out.push(...await fn)}catch(e){console.warn('[VYBE] Google search failed',e)}};if(t.length){const types=categorySearchTypes(t);if(types.length)await add(searchNearbyGooglePlaces(o.userLat,o.userLng,r,types));for(const c of t){const d=VYBE_CATEGORY_DEFINITIONS[c];for(const text of d.googleTextQueries)for(const type of d.googleIncludedTypes)await add(searchGooglePlacesText(text,o.userLat,o.userLng,r,type))}}else if(q)await add(searchGooglePlacesText(q,o.userLat,o.userLng,r));else await add(searchNearbyGooglePlaces(o.userLat,o.userLng,r));return out.filter(p=>p.provider==='google'&&!p.providerTypes?.some(x=>BAD_GOOGLE_TYPES.has(x)))}
async function osm(o:DiscoveryOptions,t:VybeCategory[]):Promise<Place[]>{if(o.userLat===undefined||o.userLng===undefined||!t.length)return[];const clauses=categoryOsmClauses(t);if(!clauses.length)return[];try{const r=await fetch('/api/osm-discovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat:o.userLat,lng:o.userLng,radiusMeters:Math.min(Math.max((o.radiusKm??5)*1000,100),50000),clauses})});if(!r.ok)return[];const data=await r.json() as {elements?:Array<Record<string,any>>};return(data.elements??[]).flatMap(e=>{const g=e.tags??{},n=String(g.name||g['name:fr']||g['name:ar']||'').trim(),lat=Number.isFinite(e.lat)?Number(e.lat):Number(e.center?.lat),lng=Number.isFinite(e.lon)?Number(e.lon):Number(e.center?.lon);if(!n||!Number.isFinite(lat)||!Number.isFinite(lng))return[];const c=t[0],d=VYBE_CATEGORY_DEFINITIONS[c],pt=[g.amenity,g.leisure,g.tourism,g.shop,g.sport,g.natural,g.religion].filter(Boolean) as string[],h=String(g.opening_hours||''),free=['place_of_worship','park','playground','library'].includes(g.amenity)||['park','playground'].includes(g.leisure),p:Place={id:`osm:${e.type}:${e.id}`,provider:'osm',providerPlaceId:`osm:${e.type}:${e.id}`,name:n,tagline:g.description||n,description:g.description||'',category:d.legacyCategory,canonicalCategory:c,primaryMood:d.mood,secondaryMoods:[],location:{address:[g['addr:housenumber'],g['addr:street'],g['addr:suburb'],g['addr:city']].filter(Boolean).join(', ')||n,neighborhood:g['addr:suburb']||'',city:g['addr:city']||'',lat,lng},priceLevel:free?'free':'$$',approxCostUsd:0,rating:0,reviewCount:0,baseVybeScore:58,images:[],tags:pt,providerTypes:pt,providerPrimaryType:pt[0],estimatedDuration:'',openingHours:{monday:h,tuesday:h,wednesday:h,thursday:h,friday:h,saturday:h,sunday:h},features:{isFree:free,isOutdoor:Boolean(g.leisure||g.natural),isIndoor:Boolean(g.amenity||g.shop),hasFood:['restaurant','fast_food','cafe','pub','bar'].includes(g.amenity),hasAlcohol:['bar','pub','nightclub'].includes(g.amenity),isLateNight:/24\/7|24 hours/i.test(h),isSecretGem:c==='tourist',isPetFriendly:false,isWifiFriendly:false,isPhotoSpot:false,isAccessible:false},suitableFor:['solo','friends','family','group'],website:g.website,phone:g.phone,instagram:g['contact:instagram'],reviews:[]};return[p]})}catch{return[]}}
export async function discoverPlaces(o:DiscoveryOptions):Promise<Place[]>{const t=targets(o),q=o.searchQuery?.trim()||o.filters?.searchQuery?.trim()||'',r=o.radiusKm??5;const [g,om]=await Promise.all([google(o,t),osm(o,t)]),all=dist(deduplicatePlaces([...g,...om]),o.userLat,o.userLng).filter(p=>o.userLat===undefined||o.userLng===undefined||(p.distanceKm??Infinity)<=r+.05);return rank(extras(gate(all,q,t),o.filters),o.filters?.sortBy).slice(0,MAX_RESULTS)}
