/** placesService — the ONLY place that knows how the places catalog is stored. */
import { supabase } from '../lib/supabase';
import { Place, PlaceReview } from '../types';
import { DbPlaceRow, DbReviewRow, newUuid, rowToPlace, rowToReview } from './mappers';
import { getGooglePlaceDetails } from './googlePlaces';

const assertBackend=()=>{if(!supabase)throw new Error('VYBE backend is not configured');return supabase;};
export function placeToRow(place:Place){return{
  id:place.id,external_place_id:place.providerPlaceId??null,provider:place.provider??'vybe',name:place.name,tagline:place.tagline,description:place.description,category:place.category,
  canonical_category:place.canonicalCategory??null,primary_mood:place.primaryMood,secondary_moods:place.secondaryMoods,latitude:place.location.lat,longitude:place.location.lng,address:place.location.address,neighborhood:place.location.neighborhood,city:place.location.city,
  price_level:place.priceLevel,approx_cost_usd:place.approxCostUsd,rating:place.rating,review_count:place.reviewCount,base_vybe_score:place.baseVybeScore,
  photos:place.provider==='google'?[]:place.images,tags:place.tags,provider_types:place.providerTypes??null,provider_primary_type:place.providerPrimaryType??null,estimated_duration:place.estimatedDuration,opening_hours:place.openingHours,features:place.features,suitable_for:place.suitableFor,
  website:place.website??null,phone:place.phone??null,instagram:place.instagram??null,featured:!!place.isFeatured,trending:!!place.isTrending
};}
const googleEnsureInFlight=new Map<string,Promise<void>>();
export async function ensureGooglePlaceStored(placeId:string):Promise<void>{
  if(placeId.startsWith('osm:')){
    const existing=googleEnsureInFlight.get(placeId);if(existing)return existing;
    const task=(async()=>{const db=assertBackend();const {data,error:lookupError}=await db.from('places').select('id').eq('id',placeId).maybeSingle();if(lookupError)throw lookupError;if(data?.id)return;const {data:sessionData,error:sessionError}=await db.auth.getSession();if(sessionError)throw sessionError;const token=sessionData.session?.access_token;if(!token)throw new Error('Authentication required to save an OpenStreetMap place.');const response=await fetch('/api/materialize-osm-place',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({placeId})});let payload:{id?:string;error?:string}={};try{payload=await response.json();}catch{}if(!response.ok||payload.id!==placeId)throw new Error(payload.error||'Unable to verify this OpenStreetMap place for saving.');})();
    googleEnsureInFlight.set(placeId,task);try{await task;}finally{googleEnsureInFlight.delete(placeId);}return;
  }
  if(!placeId.startsWith('google:'))return;const providerId=placeId.slice('google:'.length).trim();if(!providerId)throw new Error('Invalid Google place ID');
  const existing=googleEnsureInFlight.get(providerId);if(existing)return existing;
  const task=(async()=>{const db=assertBackend();const {data,error:lookupError}=await db.from('places').select('id').eq('id',placeId).maybeSingle();if(lookupError)throw lookupError;if(data?.id)return;const {data:sessionData,error:sessionError}=await db.auth.getSession();if(sessionError)throw sessionError;const token=sessionData.session?.access_token;if(!token)throw new Error('Authentication required to save a Google place.');const response=await fetch('/api/materialize-google-place',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({placeId:providerId})});let payload:{id?:string;error?:string}={};try{payload=await response.json();}catch{}if(!response.ok||payload.id!==placeId){await getGooglePlaceDetails(providerId).catch(()=>null);throw new Error(payload.error||'Unable to verify this Google place for saving.');}})();
  googleEnsureInFlight.set(providerId,task);try{await task;}finally{googleEnsureInFlight.delete(providerId);}
}
export function placePatchToRow(updates:Partial<Place>):Record<string,unknown>{const patch:Record<string,unknown>={};const set=(k:string,v:unknown)=>{if(v!==undefined)patch[k]=v;};set('name',updates.name);set('tagline',updates.tagline);set('description',updates.description);set('category',updates.category);set('canonical_category',updates.canonicalCategory??undefined);set('primary_mood',updates.primaryMood);set('secondary_moods',updates.secondaryMoods);if(updates.location){set('latitude',updates.location.lat);set('longitude',updates.location.lng);set('address',updates.location.address);set('neighborhood',updates.location.neighborhood);set('city',updates.location.city);}set('price_level',updates.priceLevel);set('approx_cost_usd',updates.approxCostUsd);set('rating',updates.rating);set('review_count',updates.reviewCount);set('base_vybe_score',updates.baseVybeScore);if(updates.images!==undefined&&updates.provider!=='google')set('photos',updates.images);set('tags',updates.tags);set('provider_types',updates.providerTypes);set('provider_primary_type',updates.providerPrimaryType);set('estimated_duration',updates.estimatedDuration);set('opening_hours',updates.openingHours);set('features',updates.features);set('suitable_for',updates.suitableFor);set('website',updates.website??null);set('phone',updates.phone??null);set('instagram',updates.instagram??null);set('featured',updates.isFeatured);set('trending',updates.isTrending);return patch;}
export const placesService={
  async listWithReviews():Promise<Place[]>{const db=assertBackend();const {data,error}=await db.from('places').select('*, reviews(*, profiles(display_name, avatar_url))').order('created_at',{ascending:true});if(error)throw error;return(data as unknown as Array<DbPlaceRow&{reviews:DbReviewRow[]|null}>).map(row=>{const place=rowToPlace(row);place.reviews=(row.reviews??[]).map(rowToReview).sort((a,b)=>(a.createdAt<b.createdAt?1:-1));return place;});},
  async getPublic(placeId:string):Promise<Place|null>{const db=assertBackend();const {data,error}=await db.from('places').select('*, reviews(*, profiles(display_name, avatar_url))').eq('id',placeId).maybeSingle();if(error)throw error;if(!data)return null;const row=data as unknown as DbPlaceRow&{reviews:DbReviewRow[]|null};const place=rowToPlace(row);place.reviews=(row.reviews??[]).map(rowToReview).sort((a,b)=>(a.createdAt<b.createdAt?1:-1));return place;},
  async create(place:Place):Promise<void>{const db=assertBackend();const {error}=await db.from('places').insert(placeToRow({...place,id:place.id||newUuid()}));if(error)throw error;},
  async update(placeId:string,updates:Partial<Place>):Promise<void>{const db=assertBackend();const {error}=await db.from('places').update(placePatchToRow(updates)).eq('id',placeId);if(error)throw error;},
  async remove(placeId:string):Promise<void>{const db=assertBackend();const {error}=await db.from('places').delete().eq('id',placeId);if(error)throw error;},
  async listReviewsForPlace(placeId:string):Promise<PlaceReview[]>{const db=assertBackend();const {data,error}=await db.from('reviews').select('*, profiles(display_name, avatar_url)').eq('place_id',placeId).order('created_at',{ascending:false});if(error)throw error;return(data as unknown as DbReviewRow[]).map(rowToReview);}
};
