import type { CategoryType, Place, VybeCategory as CanonicalCategory, MoodType } from '../types';
import { discoverPlaces } from '../services/discoveryService';

export type VybeCategory='gaming'|'food'|'cafe'|'nightlife'|'culture'|'outdoors'|'shopping'|'sports'|'family'|'wellness'|'services'|'stay'|'other';
export type VybeMood=MoodType;
export type VybeSource='OpenStreetMap'|'Google Places';
export interface VybeAnalysis{category:VybeCategory;mood:VybeMood;confidence:number;labels:string[];reasons:string[];score:number;}
export interface VybePlace{id:string;source:VybeSource;sourceId:string;name:string;address:string;city:string;lat:number;lng:number;distanceKm:number;phone?:string;website?:string;image?:string;rating?:number;reviewCount?:number;openingHours?:string;tags:string[];analysis:VybeAnalysis;}
export interface DiscoverOptions{lat:number;lng:number;radiusKm?:number;query?:string;category?:VybeCategory|'all'}
const legacyToCanonical:Partial<Record<VybeCategory,CanonicalCategory[]>>={gaming:['games'],food:['restaurant'],cafe:['cafe'],nightlife:['nightlife'],culture:['arts-culture','library','worship'],outdoors:['park','outdoors'],shopping:['shopping'],sports:['gym'],family:['family-kids'],wellness:['wellness'],stay:['hotel']};
const canonicalToLegacy:Partial<Record<CanonicalCategory,VybeCategory>>={games:'gaming',restaurant:'food',cafe:'cafe',nightlife:'nightlife','arts-culture':'culture',library:'culture',worship:'culture',park:'outdoors',outdoors:'outdoors',shopping:'shopping',gym:'sports','family-kids':'family',wellness:'wellness',hotel:'stay',cinema:'other',tourist:'other',entertainment:'other'};
const legacyToFilter=(c:CanonicalCategory):CategoryType|undefined=>c==='games'?'arcade-gaming':c==='restaurant'||c==='cafe'?'food-drink':c==='nightlife'?'nightlife':c==='arts-culture'||c==='library'||c==='worship'?'arts-culture':c==='park'||c==='outdoors'||c==='gym'?'outdoors-nature':c==='shopping'?'shopping-vintage':c==='family-kids'||c==='cinema'||c==='entertainment'?'entertainment':c==='wellness'||c==='hotel'?'chill-spots':c==='tourist'?'hidden-gems':undefined;
function adapt(place:Place):VybePlace{const category=canonicalToLegacy[place.canonicalCategory??'entertainment']??'other';return{id:place.id,source:place.provider==='osm'?'OpenStreetMap':'Google Places',sourceId:place.providerPlaceId??place.id,name:place.name,address:place.location.address,city:place.location.city,lat:place.location.lat,lng:place.location.lng,distanceKm:place.distanceKm??0,phone:place.phone,website:place.website,image:place.images[0],rating:place.rating,reviewCount:place.reviewCount,openingHours:Object.values(place.openingHours).filter(v=>typeof v==='string'&&v).join(' | ')||undefined,tags:place.tags,analysis:{category,mood:place.primaryMood,confidence:place.relevance?.providerIdentityConfidence??place.providerIdentityConfidence??.35,labels:[place.category],reasons:place.relevance?.reasons??[],score:place.baseVybeScore}};}
export async function discoverEverything(options:DiscoverOptions):Promise<VybePlace[]>{const canonical=options.category&&options.category!=='all'?legacyToCanonical[options.category]??[]:undefined;const categories=(canonical??[]).map(legacyToFilter).filter((v):v is CategoryType=>Boolean(v));const places=await discoverPlaces({userLat:options.lat,userLng:options.lng,radiusKm:options.radiusKm,searchQuery:options.query,filters:{categories}});return places.map(adapt);}
export function getCityLabel(lat:number,lng:number):string{if(Math.abs(lat-36.75)<.5&&Math.abs(lng-5.05)<.7)return'Béjaïa';if(Math.abs(lat-36.75)<.7&&Math.abs(lng-3.05)<.7)return'Algiers';if(Math.abs(lat-35.70)<.6&&Math.abs(lng-.65)<.6)return'Oran';if(Math.abs(lat-36.19)<.5&&Math.abs(lng-5.40)<.6)return'Sétif';if(Math.abs(lat-36.36)<.5&&Math.abs(lng-6.60)<.6)return'Constantine';return'Your area';}
