import React from 'react';
import { ArrowDownUp, ArrowRight, Check, Clock3, Compass, Gem, MapPin, RotateCcw, Sparkles, Users, WalletCards } from 'lucide-react';
import { CompanionType, FilterState, MoodType, TimeDuration } from '../../types';
import { INITIAL_MOODS } from '../../data/initialMoods';
import { useData } from '../../context/DataContext';
import { PlaceCard } from '../cards/PlaceCard';

const USD=130;
const TYPES=[
 ['mosque','mosque','Mosques','🕌','🇩🇿'],['restaurant','restaurant','Restaurants','🍽️',''],['cafe','cafe','Cafés','☕',''],['park','park','Parks','🌳',''],['cinema','cinema','Cinema','🎬',''],['gym','gym','Gyms','💪',''],['hotel','hotel','Hotels','🏨',''],['shopping','shopping','Shopping','🛍️',''],['library','library','Libraries','📚',''],['museum','museum','Museums','🏛️',''],['sports','sports center','Sports','⚽',''],['nightlife','nightlife','Nightlife','🌙',''], ['arcade','arcade gaming','Arcades','🎮',''],['music','live music','Music','🎵',''],['theatre','theatre','Theatre','🎭',''],['playground','playground','Playgrounds','🛝',''],['beach','beach','Beaches','🏖️','']
] as const;
const TIME:[TimeDuration,string,string][]=[['15min','15 min','⚡'],['30min','30 min','☕'],['1h','1 hour','⏱️'],['2h','2 hours','🌆'],['3h+','3+ hours','🚀'],['all-day','All day','🌅']];
const BUDGET=[['free','Free','$0 / 0 DZD','💸'],[10,'Under $10',`≈ ${(10*USD).toLocaleString()} DZD`,'🪙'],[25,'Under $25',`≈ ${(25*USD).toLocaleString()} DZD`,'💵'],[50,'Under $50',`≈ ${(50*USD).toLocaleString()} DZD`,'💳'],['unlimited','No limit','Any budget','✨']] as const;
const WITH:[CompanionType,string,string][]=[['solo','Solo','🎧'],['friends','Friends','🛹'],['couple','Couple','💖'],['family','Family','🏡'],['group','Squad','🎉']];
const SORT=[['vybe-score','🔥 Best VYBE match'],['rating','⭐ Highest rated'],['price-asc','💰 Lowest cost'],['distance','📍 Closest'],['trending','⚡ Trending']] as const;
const pill='rounded-xl border transition-all font-bold';

export const ExploreExperience:React.FC=()=>{
 const {filters,setFilters,filteredPlaces,places,userLocation,locationError,discoveryError,discoveryLoading,discover,requestLocationAndDiscover,setActiveTab,resetFilters}=useData();
 const type=TYPES.find(([,q])=>q.toLowerCase()===filters.searchQuery.trim().toLowerCase());
 const budget=filters.onlyFree?'free':(filters.maxBudget??'unlimited');
 const active=[filters.duration,filters.companion,filters.maxBudget!==undefined||filters.onlyFree,filters.moods.length>0,filters.onlyOpenNow,filters.onlyHiddenGems,filters.onlyLateNight].filter(Boolean).length;
 const refine=Boolean(filters.duration||filters.maxBudget!==undefined||filters.onlyFree||filters.companion||filters.moods.length||filters.onlyOpenNow||filters.onlyHiddenGems||filters.onlyLateNight||filters.priceLevels.length);
 const set=<K extends keyof FilterState>(k:K,v:FilterState[K])=>setFilters(p=>({...p,[k]:v}));
 const search=()=>{if(!userLocation){requestLocationAndDiscover();return;}discover(filters);document.getElementById('explore-results')?.scrollIntoView({behavior:'smooth'});};
 const clear=()=>{resetFilters();document.getElementById('explore-top')?.scrollIntoView({behavior:'smooth'});};
 const quick=(k:'onlyOpenNow'|'onlyFree'|'onlyHiddenGems'|'onlyLateNight')=>setFilters(p=>({...p,[k]:!p[k],...(k==='onlyFree'&&!p.onlyFree?{maxBudget:undefined}:{})}));
 const mood=(m:MoodType)=>setFilters(p=>({...p,moods:p.moods.includes(m)?p.moods.filter(x=>x!==m):[...p.moods,m]}));
 const chooseType=(q:string)=>{const next={...filters,searchQuery:filters.searchQuery.toLowerCase()===q.toLowerCase()?'':q,categories:[]};setFilters(next);if(next.searchQuery)discover(next);};
 // Raw provider/network strings (Overpass, Vercel status codes, 404/429/504 …)
 // are implementation details and must never be presented as UX.
 const rawError=discoveryError||locationError||'';
 const isTechnicalError=/OpenStreetMap|Google Places|Overpass|OSM|Vercel|quota|timed? ?out|failed|temporarily|unavailable|\b\d{3}\b/i.test(rawError);
 const emptyTitle=!userLocation
   ? 'Location is needed for nearby discovery.'
   : isTechnicalError
     ? (locationError ? 'Location unavailable — check browser permissions.' : 'Nothing nearby right now — give it another try.')
     : (rawError || 'No matches found.');
 return <div id="explore-top" className="relative overflow-hidden bg-[#F6F7FB] dark:bg-[#090A0F]">
  <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_top,rgba(204,255,0,.12),transparent_34%),radial-gradient(circle_at_80%_20%,rgba(0,240,255,.08),transparent_28%)]"/>
  <section className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-10 sm:pt-14 pb-8">
   <div className="text-center space-y-4"><div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-950 text-white dark:bg-white/10 dark:text-vybe-lime border border-white/10 text-xs font-mono font-bold tracking-[.16em]"><Sparkles className="w-3.5 h-3.5 text-vybe-lime"/> REAL-TIME CITY DISCOVERY</div><h1 className="font-display font-black text-5xl sm:text-7xl lg:text-8xl text-slate-950 dark:text-white leading-[.95]">Find your <span className="text-transparent bg-clip-text bg-gradient-to-r from-vybe-lime via-vybe-cyan to-vybe-pink">VYBE.</span></h1><p className="max-w-2xl mx-auto text-sm sm:text-lg text-slate-600 dark:text-slate-300">Pick what you want nearby. VYBE finds real places, ranks the best matches, and keeps the same results on Map.</p><div className="flex flex-wrap justify-center gap-2 text-[11px] font-mono text-slate-500"><span className="px-2.5 py-1 rounded-full border border-slate-200 dark:border-white/10">🇩🇿 Algeria</span><span className="px-2.5 py-1 rounded-full border border-slate-200 dark:border-white/10">USD / DZD</span><span className="px-2.5 py-1 rounded-full border border-slate-200 dark:border-white/10">{places.length} discovered</span></div></div>
   <div className="mt-8 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-2.5">{TYPES.map(([id,q,label,emoji,flag])=>{const on=type?.[0]===id;return <button key={id} type="button" aria-pressed={on} onClick={()=>chooseType(q)} className={`group relative min-h-24 rounded-2xl border flex flex-col items-center justify-center px-3 py-3 transition-all ${on?'bg-black text-vybe-lime border-vybe-lime shadow-neon-lime scale-[1.02]':'bg-white/80 dark:bg-vybe-dark-card/80 text-slate-800 dark:text-slate-200 border-slate-200 dark:border-vybe-dark-border hover:-translate-y-1 hover:border-vybe-lime/60'}`}><span className="text-3xl group-hover:scale-110 transition-transform">{emoji}</span><span className="mt-1 text-xs sm:text-sm font-display font-bold">{label}</span>{flag&&<span className="text-[11px]">{flag}</span>}{on&&<Check className="absolute top-2 right-2 w-4 h-4"/>}</button>})}</div>
  </section>
  <section className="relative max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pb-10"><div className="rounded-[2rem] bg-white dark:bg-vybe-dark-card border border-slate-200 dark:border-vybe-dark-border shadow-2xl overflow-hidden">
   <header className="p-5 sm:p-7 bg-gradient-to-r from-slate-950 via-slate-900 to-black text-white"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2 text-vybe-lime text-[11px] font-mono font-black tracking-[.18em]"><span className="inline-flex items-center gap-2"><Compass className="w-3.5 h-3.5"/> VYBE MATCHER</span>{active>0&&<span className="px-2 py-0.5 rounded-full bg-vybe-lime/10 border border-vybe-lime/20 tracking-normal">{active} active</span>}</div><h2 className="mt-2 font-display font-black text-2xl sm:text-3xl">Refine your results</h2><p className="text-sm text-slate-300 mt-1">Everything is optional. Adjust the vibe, then apply for a fresh nearby search.</p></div><div className="flex gap-2 self-start md:self-auto">{refine&&<button type="button" onClick={clear} className="px-3 py-2 rounded-xl bg-white/10 border border-white/10 text-xs font-bold inline-flex items-center gap-1.5"><RotateCcw className="w-3.5 h-3.5"/> Reset</button>}<button type="button" onClick={search} disabled={discoveryLoading} className="px-4 py-2.5 rounded-xl bg-vybe-lime text-black text-xs font-black uppercase tracking-wider shadow-neon-lime inline-flex items-center gap-2 disabled:opacity-60">{discoveryLoading?'Searching…':'Apply & refresh'}<ArrowRight className="w-4 h-4"/></button></div></div></header>
   <div className="p-5 sm:p-7 space-y-6">
    <div className="rounded-2xl border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-vybe-dark-surface/50 p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="text-[10px] font-mono font-black uppercase tracking-[.18em] text-slate-400">Current target</div><div className="mt-1 flex flex-wrap items-center gap-2 font-display font-black text-lg">{type?`${type[3]} ${type[2]} ${type[4]}`:'🌍 All nearby places'}{userLocation&&<span className="text-[10px] px-2 py-1 rounded-full bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 font-mono">LOCATION READY</span>}</div></div><div className="text-xs font-mono text-slate-500 text-left sm:text-right"><div>{filteredPlaces.length} matches</div><div>{places.length} discovered</div></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><Group icon={<Clock3 className="w-4 h-4 text-vybe-cyan"/>} title="Time" note="OPTIONAL"><div className="grid grid-cols-3 gap-2">{TIME.map(([v,l,i])=><button key={v} type="button" aria-pressed={filters.duration===v} onClick={()=>set('duration',filters.duration===v?undefined:v)} className={`${pill} p-2.5 text-[11px] ${filters.duration===v?'bg-black text-vybe-lime border-vybe-lime shadow-neon-lime':'bg-slate-50 dark:bg-vybe-dark-surface border-slate-200 dark:border-vybe-dark-border'}`}><span>{i}</span><span>{l}</span></button>)}</div></Group><Group icon={<WalletCards className="w-4 h-4 text-vybe-lime"/>} title="Budget" note="DZD"><div className="grid grid-cols-3 gap-2">{BUDGET.map(([v,l,s,i])=>{const on=budget===v;return <button key={String(v)} type="button" aria-pressed={on} onClick={()=>setFilters(p=>({...p,maxBudget:typeof v==='number'?v:undefined,onlyFree:v==='free'}))} className={`${pill} min-h-[72px] p-2 text-[11px] ${on?'bg-black text-vybe-lime border-vybe-lime shadow-neon-lime':'bg-slate-50 dark:bg-vybe-dark-surface border-slate-200 dark:border-vybe-dark-border'}`}><div>{i}</div><div>{l}</div><div className="text-[9px] font-mono opacity-70">{s}</div></button>})}</div></Group><Group icon={<Users className="w-4 h-4 text-vybe-pink"/>} title="With" note="OPTIONAL"><div className="grid grid-cols-3 gap-2">{WITH.map(([v,l,i])=><button key={v} type="button" aria-pressed={filters.companion===v} onClick={()=>set('companion',filters.companion===v?undefined:v)} className={`${pill} p-2.5 text-[11px] ${filters.companion===v?'bg-black text-vybe-lime border-vybe-lime shadow-neon-lime':'bg-slate-50 dark:bg-vybe-dark-surface border-slate-200 dark:border-vybe-dark-border'}`}><span>{i}</span><span>{l}</span></button>)}</div></Group></div>
    <div className="rounded-2xl border border-slate-200 dark:border-white/10 p-4 sm:p-5 bg-slate-50/70 dark:bg-vybe-dark-surface/30"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2 font-display font-bold"><Sparkles className="w-4 h-4 text-vybe-citrus"/> Vibe</div><span className="text-xs font-mono text-slate-400">{filters.moods.length} selected</span></div><div className="flex flex-wrap gap-2">{INITIAL_MOODS.map(m=>{const on=filters.moods.includes(m.id);return <button key={m.id} type="button" aria-pressed={on} onClick={()=>mood(m.id)} className={`px-3 py-1.5 rounded-full text-xs border inline-flex items-center gap-1.5 ${on?'bg-black text-vybe-lime border-vybe-lime shadow-neon-lime':'bg-white dark:bg-vybe-dark-surface border-slate-200 dark:border-vybe-dark-border'}`}><span>{m.emoji}</span><span>{m.label}</span>{on&&<Check className="w-3 h-3"/>}</button>})}</div></div>
    <div className="rounded-2xl border border-slate-200 dark:border-white/10 p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="font-display font-bold">⚡ Quick filters</div><div className="text-xs text-slate-500 mt-0.5">Strict filters remove places that do not match.</div></div><div className="flex flex-wrap gap-2">{([['onlyOpenNow','🟢 Open now'],['onlyFree','💸 Free only'],['onlyHiddenGems','💎 Hidden gems'],['onlyLateNight','🌙 Late night']] as const).map(([k,l])=><button key={k} type="button" aria-pressed={Boolean(filters[k])} onClick={()=>quick(k)} className={`px-3 py-1.5 rounded-full text-xs border ${filters[k]?'bg-black text-vybe-lime border-vybe-lime shadow-neon-lime':'bg-slate-50 dark:bg-vybe-dark-surface border-slate-200 dark:border-vybe-dark-border'}`}>{l}</button>)}</div></div></div>
   </div>
  </div></section>
  <section id="explore-results" className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-16 space-y-6">
   <div className="sticky top-0 z-20 rounded-3xl bg-white/95 dark:bg-vybe-dark-card/95 backdrop-blur border border-slate-200 dark:border-vybe-dark-border p-3 sm:p-4 shadow-lg"><div className="flex flex-col md:flex-row gap-3 md:items-center justify-between"><div className="flex flex-wrap gap-2 text-xs font-mono"><span className="px-2.5 py-1.5 rounded-full bg-slate-100 dark:bg-vybe-dark-surface"><b>{filteredPlaces.length}</b> matching places</span>{type&&<span className="px-2.5 py-1.5 rounded-full bg-vybe-lime/10 text-vybe-lime font-bold">{type[3]} {type[2]}</span>}{active>0&&<span className="px-2.5 py-1.5 rounded-full bg-vybe-cyan/10 font-bold">{active} filters</span>}</div><div className="flex items-center gap-2"><ArrowDownUp className="w-3.5 h-3.5 text-slate-400"/><select aria-label="Sort results" value={filters.sortBy} onChange={e=>set('sortBy',e.target.value as FilterState['sortBy'])} className="px-3 py-2 rounded-xl bg-slate-50 dark:bg-vybe-dark-surface border border-slate-200 dark:border-vybe-dark-border text-xs font-bold">{SORT.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{refine&&<button type="button" onClick={clear} className="px-3 py-2 rounded-xl bg-rose-500/10 text-rose-500 text-xs font-bold"><RotateCcw className="w-3.5 h-3.5 inline"/> Clear</button>}</div></div></div>
   <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><div className="inline-flex items-center gap-1.5 text-xs font-mono font-black tracking-wider text-vybe-lime uppercase"><Sparkles className="w-3.5 h-3.5"/> VYBE recommendations</div><h2 className="mt-1 font-display font-black text-3xl sm:text-4xl text-slate-950 dark:text-white">{type?`${type[3]} ${type[2]} near you`:'Best places near you'}</h2></div><button type="button" onClick={()=>setActiveTab('map')} className="inline-flex items-center gap-2 text-xs font-bold text-slate-600 dark:text-slate-300 hover:text-vybe-lime"><MapPin className="w-4 h-4 text-vybe-cyan"/> Open map <ArrowRight className="w-3.5 h-3.5"/></button></div>
   {filteredPlaces.length===0?<div className="rounded-3xl bg-white dark:bg-vybe-dark-card border border-slate-200 dark:border-vybe-dark-border p-12 text-center space-y-4"><div className="text-5xl">🛸</div><h3 className="font-display font-black text-xl">{emptyTitle}</h3><p className="text-sm text-slate-500">{isTechnicalError?'Our discovery service is briefly unavailable. Try another place type or search again in a moment.':'Try another place type, clear a filter, or search again.'}</p>{!userLocation?<button type="button" onClick={requestLocationAndDiscover} className="px-5 py-2.5 rounded-full bg-vybe-lime text-black text-sm font-black">Use my location</button>:<button type="button" onClick={search} disabled={discoveryLoading} className="px-5 py-2.5 rounded-full bg-vybe-lime text-black text-sm font-black">{discoveryLoading?'Searching…':'Search again'}</button>}</div>:<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{filteredPlaces.map(({place,scoreInfo})=><PlaceCard key={place.id} place={place} scoreInfo={scoreInfo}/>)}</div>}
   <div className="rounded-3xl overflow-hidden border border-white/10 bg-gradient-to-r from-slate-950 via-vybe-dark-card to-black text-white p-8 sm:p-10"><div className="max-w-2xl space-y-3"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/10 text-vybe-cyan text-[11px] font-mono font-bold"><Gem className="w-3.5 h-3.5"/> LIVE CITY RADAR</div><h3 className="font-display font-black text-3xl sm:text-4xl">Same places. Same filters. Same map.</h3><p className="text-sm text-slate-300">Explore and Map share the same discovered place collection and active filters.</p><button type="button" onClick={()=>setActiveTab('map')} className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-white text-black text-xs font-black uppercase tracking-wider">Open interactive map <ArrowRight className="w-4 h-4"/></button></div></div>
  </section>
 </div>;
};
const Group:React.FC<{icon:React.ReactNode;title:string;note:string;children:React.ReactNode}>=({icon,title,note,children})=><div className="rounded-2xl border border-slate-200 dark:border-white/10 p-4 bg-white dark:bg-transparent"><div className="flex items-center justify-between gap-3 mb-3"><div className="flex items-center gap-2 font-display font-bold">{icon}{title}</div><span className="text-[10px] font-mono text-slate-400">{note}</span></div>{children}</div>;
