export type Category = 'all' | 'gaming' | 'food' | 'cafe' | 'nightlife' | 'outdoors' | 'culture' | 'shopping' | 'sports' | 'family' | 'wellness' | 'stay' | 'services';
export type Mood = 'all' | 'gaming' | 'chill' | 'party' | 'hungry' | 'curious' | 'outdoor' | 'energetic' | 'romantic' | 'creative' | 'explore';
export type Place = {
  id:string; name:string; lat:number; lng:number; address:string; type:string; tags:string[];
  category:Exclude<Category,'all'>; mood:Exclude<Mood,'all'>; distanceKm:number; score:number; confidence:number;
  rating?:number; reviews?:number; price:'free'|'$'|'$$'|'$$$'; indoor:boolean; outdoor:boolean; reason:string;
  source:'OpenStreetMap'; photoFallback?:string; website?:string; phone?:string; osmUrl:string;
};
export type City={id:string;label:string;lat:number;lng:number};

export const CITIES:City[]=[
  {id:'bejaia',label:'Béjaïa',lat:36.7525,lng:5.0556},{id:'algiers',label:'Alger',lat:36.7538,lng:3.0588},
  {id:'oran',label:'Oran',lat:35.6971,lng:-0.6308},{id:'setif',label:'Sétif',lat:36.1898,lng:5.4108},
  {id:'constantine',label:'Constantine',lat:36.365,lng:6.6147},
];

const QUERIES:Record<Exclude<Category,'all'>,string>={
  gaming:'nwr["amenity"~"^(internet_cafe|arcade|amusement_arcade|bowling_alley)$"];nwr["shop"="video_games"]',
  food:'nwr["amenity"~"^(restaurant|fast_food|food_court|ice_cream)$"]', cafe:'nwr["amenity"="cafe"]',
  nightlife:'nwr["amenity"~"^(bar|pub|nightclub|disco|biergarten)$"]',
  outdoors:'nwr["leisure"~"^(park|garden|playground|nature_reserve|picnic_table)$"];nwr["natural"~"^(beach|peak|wood)$"]',
  culture:'nwr["amenity"~"^(library|theatre|cinema|arts_centre|community_centre)$"];nwr["tourism"~"^(museum|gallery|attraction)$"]',
  shopping:'nwr["shop"];nwr["amenity"="marketplace"]',
  sports:'nwr["leisure"~"^(sports_centre|stadium|pitch|fitness_centre|swimming_pool)$"]',
  family:'nwr["leisure"="playground"];nwr["tourism"~"^(zoo|aquarium)$"];nwr["amenity"="childcare"]',
  wellness:'nwr["leisure"="fitness_centre"];nwr["amenity"~"^(spa|clinic|dentist)$"]',
  stay:'nwr["tourism"~"^(hotel|hostel|guest_house|motel|camp_site)$"]',
  services:'nwr["amenity"~"^(hospital|clinic|pharmacy|bank|post_office|fuel|car_wash)$"]',
};
const ALL_CATEGORIES=(Object.keys(QUERIES) as Array<Exclude<Category,'all'>>);
const clean=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const escapeRegex=(v:string)=>v.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
function haversine(a:number,b:number,c:number,d:number){const r=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return r*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
function classify(name:string,tags:string[],hint:Category):Exclude<Category,'all'>{const s=clean(`${name} ${tags.join(' ')}`);if(/arcade|gaming|internet cafe|bowling|video game|jeux video/.test(s))return'gaming';if(/restaurant|pizza|burger|fast.?food|snack|ice.?cream/.test(s))return'food';if(/cafe|coffee/.test(s))return'cafe';if(/bar|pub|club|disco|night/.test(s))return'nightlife';if(/park|garden|beach|plage|playground|picnic|nature_reserve/.test(s))return'outdoors';if(/museum|library|theatre|cinema|arts|gallery|culture/.test(s))return'culture';if(/mall|market|shop|store|boutique|supermarket/.test(s))return'shopping';if(/sport|stadium|gym|fitness|pitch|swimming/.test(s))return'sports';if(/hotel|hostel|guest.?house|motel|camp/.test(s))return'stay';if(/spa|wellness|dentist|clinic/.test(s))return'wellness';return hint==='all'?'services':hint as Exclude<Category,'all'>;}
function getMood(c:Exclude<Category,'all'>):Exclude<Mood,'all'>{return ({gaming:'gaming',food:'hungry',cafe:'chill',nightlife:'party',outdoors:'outdoor',culture:'curious',shopping:'explore',sports:'energetic',family:'explore',wellness:'chill',stay:'chill',services:'explore'})[c];}
function scorePlace(distanceKm:number,radiusKm:number,rating:number|undefined,reviews:number|undefined,complete:number,hasImage:boolean,category:Category){const distance=Math.max(0,34-(distanceKm/radiusKm)*24),ratingScore=rating?Math.min(18,rating*3.2):0,reviewScore=reviews?Math.min(10,Math.log10(reviews+1)*3.2):0;return Math.round(Math.min(100,distance+ratingScore+reviewScore+complete*22+(hasImage?5:0)+(category==='gaming'?5:0)));}
async function overpass(query:string):Promise<{elements:any[]}>{const body=new URLSearchParams({data:query});for(const endpoint of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.private.coffee/api/interpreter']){try{const response=await fetch(endpoint,{method:'POST',body});if(response.ok)return await response.json() as {elements:any[]};}catch{/* next mirror */}}throw new Error('Discovery service unavailable');}
function buildAround(clause:string,r:number,c:City){const i=clause.indexOf('[');return `${clause.slice(0,i)}(around:${r},${c.lat},${c.lng})${clause.slice(i)}`;}
function queryForCategory(c:City,r:number,category:Exclude<Category,'all'>){const clauses=QUERIES[category].split(';').map(v=>buildAround(v,r,c)).join(';');return `[out:json][timeout:45];(${clauses};);out center tags;`;}
function queryForSearch(c:City,r:number,text:string){const q=escapeRegex(text.trim());return `[out:json][timeout:45];(nwr(around:${r},${c.lat},${c.lng})["name"~"${q}",i];nwr(around:${r},${c.lat},${c.lng})["brand"~"${q}",i];nwr(around:${r},${c.lat},${c.lng})["operator"~"${q}",i];);out center tags;`;}
function mapElement(element:any,city:City,radius:number,hint:Category):Place|null{const lat=Number(element.lat??element.center?.lat),lng=Number(element.lon??element.center?.lon),name=String(element.tags?.name||'').trim();if(!name||!Number.isFinite(lat)||!Number.isFinite(lng))return null;const raw=element.tags||{},tags=Object.entries(raw).map(([k,v])=>`${k}:${String(v)}`),category=classify(name,tags,hint),distanceKm=haversine(city.lat,city.lng,lat,lng);if(distanceKm>radius+.25)return null;const ratingN=Number(raw.rating||raw.stars),reviewsN=Number(raw.reviews||raw.review_count),rating=Number.isFinite(ratingN)&&ratingN>0?ratingN:undefined,reviews=Number.isFinite(reviewsN)&&reviewsN>0?reviewsN:undefined;const street=[raw['addr:street'],raw['addr:housenumber']].filter(Boolean).join(' '),address=String(raw['addr:full']||street||raw['addr:place']||city.label),photoFallback=typeof raw.image==='string'?raw.image:undefined,website=typeof raw.website==='string'?raw.website:typeof raw['contact:website']==='string'?raw['contact:website']:undefined,phone=typeof raw.phone==='string'?raw.phone:typeof raw['contact:phone']==='string'?raw['contact:phone']:undefined,complete=[address!==city.label,website,phone,raw.opening_hours,rating].filter(Boolean).length/5,txt=clean(`${name} ${tags.join(' ')}`),outdoor=['outdoors','sports','family'].includes(category)||raw.outdoor_seating==='yes';const price:Place['price']=/park|beach|plage|library|playground|mosque|church/.test(txt)?'free':/hotel|nightclub|spa|restaurant/.test(txt)?'$$$':'$$';const confidence=Math.max(.58,Math.min(.99,.58+complete*.25+(rating?.08:0)+(photoFallback?.04:0)));const score=scorePlace(distanceKm,radius,rating,reviews,complete,Boolean(photoFallback),category);return {id:`osm-${element.type}-${element.id}`,name,lat,lng,address,type:String(raw.amenity||raw.leisure||raw.shop||raw.tourism||'place'),tags,category,mood:getMood(category),distanceKm,score,confidence,rating,reviews,price,indoor:!outdoor,outdoor,reason:`${category} · ${getMood(category)} · ${distanceKm.toFixed(1)} km · ${Math.round(confidence*100)}% confidence`,source:'OpenStreetMap',photoFallback,website,phone,osmUrl:`https://www.openstreetmap.org/${element.type}/${element.id}`};}

async function settledQueries(queries:string[]):Promise<{elements:any[]}[]>{const results=await Promise.allSettled(queries.map(overpass));return results.flatMap((result)=>result.status==='fulfilled'?[result.value]:[]);}
export async function discover(city:City,radiusKm:number,search:string,category:Category):Promise<Place[]>{const radius=Math.max(1,Math.min(20,radiusKm)),meters=radius*1000;const responses=search.trim()?await settledQueries([queryForSearch(city,meters,search)]):category==='all'?await settledQueries(ALL_CATEGORIES.map((item)=>queryForCategory(city,meters,item))):await settledQueries([queryForCategory(city,meters,category)]);const seen=new Set<string>(),places:Place[]=[];for(const response of responses)for(const element of response.elements||[]){const place=mapElement(element,city,radius,category);if(!place||seen.has(place.id))continue;if(category!=='all'&&category!==place.category)continue;seen.add(place.id);places.push(place);}if(!places.length)throw new Error(search.trim()?'Aucun résultat pour cette recherche':'Aucun lieu trouvé dans cette zone');return places.sort((a,b)=>b.score-a.score||a.distanceKm-b.distanceKm).slice(0,1000);}
