import type { Place } from './engine';

type GooglePhoto={url:string;author?:string;authorUrl?:string;mapsUrl?:string};
type GooglePlace={id?:string;displayName?:{text?:string};location?:{lat?:number|(()=>number);lng?:number|(()=>number)};photos?:Array<{getURI:(options?:{maxWidth?:number;maxHeight?:number})=>string;authorAttributions?:Array<{displayName?:string;uri?:string}>;googleMapsURI?:string}>;googleMapsURI?:string};
type PlacesLibrary={Place?:{searchByText:(request:Record<string,unknown>)=>Promise<{places?:GooglePlace[]}>}};
type GoogleWindow=Window&{google?:{maps?:{importLibrary?:(name:string)=>Promise<unknown>}}};
let placesPromise:Promise<PlacesLibrary|null>|null=null;
const photoCache=new Map<string,GooglePhoto|null>();
const photoInflight=new Map<string,Promise<GooglePhoto|null>>();
const apiKey=()=>String(import.meta.env.VITE_GOOGLE_MAPS_API_KEY||'').trim();
function numberValue(value:number|(()=>number)|undefined){return typeof value==='function'?value():value;}
function normalize(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();}
function similarity(a:string,b:string){const left=normalize(a).split(' ').filter(Boolean),right=new Set(normalize(b).split(' ').filter(Boolean));return left.length?left.filter((token)=>right.has(token)).length/left.length:0;}
async function waitForMaps(maxMs=9000){const start=Date.now();while(Date.now()-start<maxMs){if((window as GoogleWindow).google?.maps?.importLibrary)return true;await new Promise((resolve)=>window.setTimeout(resolve,120));}return false;}
async function loadPlacesLibrary():Promise<PlacesLibrary|null>{if(!apiKey())return null;if(placesPromise)return placesPromise;placesPromise=(async()=>{const win=window as GoogleWindow;if(!win.google?.maps?.importLibrary){let script=document.querySelector<HTMLScriptElement>('script[data-vybe-google-places]');if(!script){script=document.createElement('script');script.async=true;script.defer=true;script.dataset.vybeGooglePlaces='1';script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(apiKey())}&loading=async&libraries=places`;document.head.appendChild(script);}if(!(await waitForMaps()))return null;}const importLibrary=(window as GoogleWindow).google?.maps?.importLibrary;if(!importLibrary)return null;return await importLibrary('places') as PlacesLibrary;})().catch(()=>null);return placesPromise;}
export const googlePhotosEnabled=()=>Boolean(apiKey());
export async function findGooglePhoto(place:Place):Promise<GooglePhoto|null>{const key=place.id;if(photoCache.has(key))return photoCache.get(key)??null;const existing=photoInflight.get(key);if(existing)return existing;const task=(async()=>{const library=await loadPlacesLibrary(),PlaceClass=library?.Place;if(!PlaceClass)return null;try{const {places=[]}=await PlaceClass.searchByText({textQuery:`${place.name}, ${place.address}, Algérie`,fields:['id','displayName','location','photos','googleMapsURI'],locationBias:{center:{lat:place.lat,lng:place.lng},radius:900},maxResultCount:5,language:'fr',region:'dz'});const match=places.map((candidate)=>{const lat=numberValue(candidate.location?.lat),lng=numberValue(candidate.location?.lng),distance=Number.isFinite(lat)&&Number.isFinite(lng)?Math.hypot(Number(lat)-place.lat,Number(lng)-place.lng):99,nameScore=similarity(place.name,candidate.displayName?.text||'');return{candidate,score:nameScore*6-Math.min(distance*100,6)};}).sort((a,b)=>b.score-a.score).find((entry)=>entry.score>0.8)?.candidate;if(!match)return null;const photo=match.photos?.[0];if(!photo)return null;const attribution=photo.authorAttributions?.[0];return{url:photo.getURI({maxWidth:900,maxHeight:620}),author:attribution?.displayName,authorUrl:attribution?.uri,mapsUrl:photo.googleMapsURI||match.googleMapsURI};}catch{return null;}})();photoInflight.set(key,task);try{const result=await task;photoCache.set(key,result);return result;}finally{photoInflight.delete(key);}}
