import React, { useEffect, useRef, useState } from 'react';
import { Place } from '../../types';
import { googleMapsConfig } from '../../lib/env';
import { loadGoogleMaps } from '../../lib/googleMapsLoader';
import { INITIAL_MOODS } from '../../data/initialMoods';
interface GoogleMapProps { places: Place[]; onMarkerClick?: (place: Place) => void; selectedPlace?: Place | null; userLocation?: { lat:number; lng:number } | null; onError?: (message:string)=>void; }
type AnyMarker=google.maps.marker.AdvancedMarkerElement|google.maps.Marker;
function getPlaceMarkerEmoji(place:Place):string{const category=place.canonicalCategory;switch(category){case'games':return'🎮';case'cinema':return'🎬';case'restaurant':return'🍽️';case'cafe':return'☕';case'hotel':return'🏨';case'library':return'📚';case'worship':return'🕌';case'gym':return'🏋️';case'park':case'outdoors':return'🌳';case'shopping':return'🛍️';case'nightlife':return'🎵';case'family-kids':return'👨‍👩‍👧‍👦';case'tourist':return'🏛️';case'arts-culture':return'🎭';case'wellness':return'🧘';case'entertainment':return'🎡';default:return'📍';}}
export const GoogleMap:React.FC<GoogleMapProps>=({places,onMarkerClick,selectedPlace,userLocation,onError})=>{const mapRef=useRef<HTMLDivElement>(null);const googleMapRef=useRef<google.maps.Map|null>(null);const markersRef=useRef<AnyMarker[]>([]);const onLoadCallbackRef=useRef(onMarkerClick);const markerRef=useRef<{advanced:typeof google.maps.marker.AdvancedMarkerElement|null;classic:typeof google.maps.Marker|null}>({advanced:null,classic:null});const[mapError,setMapError]=useState<string|null>(null);const[mapLoaded,setMapLoaded]=useState(false);const defaultCenter={lat:20,lng:0};onLoadCallbackRef.current=onMarkerClick;const useAdvancedMarkers=Boolean(googleMapsConfig.mapId?.trim());
const clearMarkers=()=>{markersRef.current.forEach(marker=>{try{const advanced=marker as google.maps.marker.AdvancedMarkerElement;if(advanced&&typeof advanced==='object'&&'map'in advanced){advanced.map=null;return}}catch{}try{(marker as google.maps.Marker).setMap(null)}catch{}});markersRef.current=[]};
useEffect(()=>{let cancelled=false;let mapInstance:google.maps.Map|null=null;const initializeMap=async()=>{if(!googleMapsConfig.apiKey){const message='Google Maps API key is not configured; using the legacy map fallback.';setMapError(message);onError?.(message);return}if(!mapRef.current)return;try{const{Map,AdvancedMarkerElement,Marker}=await loadGoogleMaps();if(cancelled||!mapRef.current)return;markerRef.current={advanced:AdvancedMarkerElement,classic:Marker};const map=new Map(mapRef.current,{center:userLocation||defaultCenter,zoom:userLocation?14:2,...(googleMapsConfig.mapId?.trim()?{mapId:googleMapsConfig.mapId.trim()}:{}),zoomControl:true,mapTypeControl:false,streetViewControl:false,fullscreenControl:true});mapInstance=map;googleMapRef.current=map;setMapLoaded(true);const mapContainer=mapRef.current;let tilesLoaded=false;let watchdog:number|undefined;const stopWatchdog=()=>{if(watchdog!==undefined){window.clearInterval(watchdog);watchdog=undefined}};const failGoogle=()=>{if(cancelled)return;const message='Google Maps tiles could not load (API key or quota problem). Showing the fallback map.';console.warn('[GoogleMap]',message);setMapError(message);onError?.(message)};try{map.addListener('tilesloaded',()=>{tilesLoaded=true;stopWatchdog()})}catch{}const startedAt=Date.now();watchdog=window.setInterval(()=>{if(cancelled||tilesLoaded||!mapContainer||!mapContainer.isConnected){stopWatchdog();return}if(mapContainer.querySelector('.gm-err-container')){stopWatchdog();failGoogle();return}const hasAnyProgress=!!mapContainer.querySelector('.gm-style, canvas');if(!hasAnyProgress&&Date.now()-startedAt>9000){stopWatchdog();failGoogle()}},2000);window.setTimeout(()=>{if(watchdog!==undefined)stopWatchdog()},30000)}catch(error){const message=error instanceof Error?error.message:'Unknown Google Maps error';console.error('[GoogleMap] Google Maps initialization error:',message);if(!cancelled){setMapError(message);onError?.(message)}}};initializeMap();return()=>{cancelled=true;clearMarkers();if(mapInstance)mapInstance=null;googleMapRef.current=null;markerRef.current={advanced:null,classic:null};setMapLoaded(false)}} , [userLocation]);
useEffect(()=>{if(!mapLoaded||!googleMapRef.current)return;const map=googleMapRef.current;clearMarkers();const advancedCtor=markerRef.current.advanced;const classicCtor=markerRef.current.classic;places.forEach(place=>{const lat=place.location?.lat,lng=place.location?.lng;if(lat==null||lng==null||!Number.isFinite(lat)||!Number.isFinite(lng))return;try{const moodObj=INITIAL_MOODS.find(m=>m.id===place.primaryMood);const emoji=getPlaceMarkerEmoji(place);const color=moodObj?.accentColor||'#CCFF00';const isSelected=selectedPlace?.id===place.id;const position={lat,lng};const openPlace=()=>onLoadCallbackRef.current?.(place);if(useAdvancedMarkers&&advancedCtor){const markerContent=document.createElement('div');markerContent.className=`custom-map-marker group relative cursor-pointer${isSelected?' selected':''}`;markerContent.style.cssText=`width:46px;height:46px;border-radius:14px;overflow:hidden;border:2px solid #000;box-shadow:0 4px 14px rgba(0,0,0,.35);background:#111;position:relative;transform:${isSelected?'scale(1.25)':'scale(1)'};z-index:${isSelected?'20':'1'};transition:transform .2s ease;`;const imageUrl=place.images.find(image=>image?.trim().toLowerCase().startsWith('http'))?.trim();const fallback=document.createElement('span');fallback.textContent=emoji;fallback.style.cssText=`position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:24px;background:${color};`;if(imageUrl){const image=document.createElement('img');image.src=imageUrl;image.alt=place.name;image.loading='lazy';image.style.cssText='width:100%;height:100%;object-fit:cover;display:block;';image.onerror=()=>{image.remove();if(!markerContent.contains(fallback))markerContent.appendChild(fallback)};markerContent.appendChild(image)}if(!markerContent.contains(fallback))markerContent.appendChild(fallback);const marker=new advancedCtor({map,position,content:markerContent,title:place.name,zIndex:isSelected?1000:1});marker.addListener('gmp-click',openPlace);markersRef.current.push(marker);return}if(classicCtor){const marker=new classicCtor({map,position,title:place.name,zIndex:isSelected?1000:1,label:{text:emoji,fontSize:'16px',color:'#111111'}});marker.addListener('click',openPlace);markersRef.current.push(marker)}}catch(error){console.warn('[GoogleMap] Skipped marker for',place.name,error)}})},[places,mapLoaded,selectedPlace,useAdvancedMarkers]);
useEffect(()=>{if(!googleMapRef.current||!selectedPlace?.location)return;const{lat,lng}=selectedPlace.location;if(lat==null||lng==null||!Number.isFinite(lat)||!Number.isFinite(lng))return;try{googleMapRef.current.panTo({lat,lng});googleMapRef.current.setZoom(17)}catch(error){console.warn('[GoogleMap] Could not center selected place',error)}},[selectedPlace]);
if(mapError)return null;return <div ref={mapRef} className="w-full h-full rounded-3xl overflow-hidden" style={{minHeight:'550px'}} aria-label="Google Maps"/>};
